server {
    listen 80;
    server_name localhost;

    #SSL configuración
    ssl_certificate /etc/nginx/certs/nginx.crt;
    ssl_certificate_key /etc/nginx/certs/nginx.key;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Reenvío de API al backend
    location /api/ {
        proxy_pass https://localhost:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}